services:
  # BASE DE DONNÉES
  db:
    image: postgres:17-alpine
    container_name: aci_postgres
    restart: always
    environment:
      POSTGRES_USER: aci
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aci_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # BACKEND (NestJS)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: aci_backend
    env_file: .env 
    restart: always
    ports:
      - "3001:3001" # Port exposé pour le load-balancer
    environment:
      DATABASE_URL: "postgresql://aci:${POSTGRES_PASSWORD}@db:5432/aci_portal?schema=public"
    volumes:
      - ./uploads:/uploads
    depends_on:
      - db

  # FRONTEND (Next.js)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: aci_frontend
    restart: always
    ports:
      - "3000:3000" # Port exposé pour le load-balancer
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  postgres_data: