services:
  # BASE DE DONNÉES
  db:
    image: postgres:17-alpine
    container_name: aci_postgres
    restart: always
    environment:
      POSTGRES_USER: aci
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: aci_portal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # BACKEND (NestJS)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: aci_backend
    env_file: .env # Indique à Docker de lire le fichier à la racine
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://aci:123456@db:5432/aci_portal?schema=public"
    volumes:
    - ./uploads:/uploads
    depends_on:
      - db

  # FRONTEND (Next.js)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: aci_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Correction de l'indentation ici (2 espaces de plus)
      NEXT_PUBLIC_API_URL: "https://acitechnology.eu/api" 
    depends_on:
      - backend
  
  # REVERSE PROXY (Caddy)
  caddy:
    image: caddy:latest
    container_name: aci_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: