services:
  # BASE DE DONNÉES
  db:
    image: postgres:17-alpine
    container_name: aci_postgres
    restart: always
    environment:
      POSTGRES_USER: aci
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Utilise la variable du .env
      POSTGRES_DB: aci_portal
    # On retire "ports" pour la sécurité : seul le backend y aura accès en interne
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # BACKEND (NestJS)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: aci_backend
    env_file: .env 
    restart: always
    environment:
      DATABASE_URL: "postgresql://aci:${DB_PASSWORD}@db:5432/aci_portal?schema=public"
    volumes:
      - ./uploads:/uploads
    depends_on:
      - db

  # FRONTEND (Next.js)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        # Important pour que Next.js build avec la bonne URL d'API
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: aci_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
  
  # REVERSE PROXY (Caddy)
  caddy:
    image: caddy:latest
    container_name: aci_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: